[0m15:38:14.910285 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1034e4470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f60f50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f60bc0>]}


============================== 15:38:14.912908 | dadddada-ebac-4388-9b30-70c0af00ee77 ==============================
[0m15:38:14.912908 [info ] [MainThread]: Running with dbt=1.8.7
[0m15:38:14.913234 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/gregorytomy/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -s refined_dim_location', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:38:14.913533 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gregorytomy/chi_traffic/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:38:14.914353 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.037507333, "process_user_time": 0.555768, "process_kernel_time": 0.071603, "process_mem_max_rss": "92553216", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:38:14.914667 [debug] [MainThread]: Command `dbt run` failed at 15:38:14.914621 after 0.04 seconds
[0m15:38:14.914850 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c81c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1034e40b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f60bc0>]}
[0m15:38:14.915015 [debug] [MainThread]: Flushing usage events
[0m11:40:34.924298 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a7d4bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a9627b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a961ee0>]}


============================== 11:40:34.927118 | aa2e0726-8b19-4d3a-803d-d2bcbc87fed4 ==============================
[0m11:40:34.927118 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:40:34.927488 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/gregorytomy/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt seed', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:40:34.927880 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gregorytomy/chi_traffic/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:40:34.928753 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_wall_clock_time": 0.03382004, "process_user_time": 0.558289, "process_kernel_time": 0.087836, "process_mem_max_rss": "91095040", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:40:34.929139 [debug] [MainThread]: Command `dbt seed` failed at 11:40:34.929091 after 0.03 seconds
[0m11:40:34.929379 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a41ad80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a796930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a7d4ad0>]}
[0m11:40:34.929605 [debug] [MainThread]: Flushing usage events
[0m11:22:09.181478 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10259c860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100aec950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044bcad0>]}


============================== 11:22:09.184095 | ffd780ae-2bc0-4ba2-a5fe-14a67551bfee ==============================
[0m11:22:09.184095 [info ] [MainThread]: Running with dbt=1.8.7
[0m11:22:09.184409 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/gregorytomy/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test -s refined_dim_location', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:22:09.184697 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gregorytomy/chi_traffic/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:22:09.185983 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.038867, "process_user_time": 0.560796, "process_kernel_time": 0.096417, "process_mem_max_rss": "92569600", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:22:09.186345 [debug] [MainThread]: Command `dbt test` failed at 11:22:09.186292 after 0.04 seconds
[0m11:22:09.186530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10405e270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1041a1820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1040b5dc0>]}
[0m11:22:09.186694 [debug] [MainThread]: Flushing usage events
[0m09:40:48.724362 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104124770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104bf9280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104bf8ef0>]}


============================== 09:40:48.727726 | 0708c9ab-e151-4f86-97bb-05caa2a2fe0e ==============================
[0m09:40:48.727726 [info ] [MainThread]: Running with dbt=1.8.7
[0m09:40:48.728098 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/gregorytomy/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build -s staging_crash', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:40:48.728476 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gregorytomy/chi_traffic/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:40:48.729555 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.03771925, "process_user_time": 0.570919, "process_kernel_time": 0.105444, "process_mem_max_rss": "91734016", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m09:40:48.730089 [debug] [MainThread]: Command `dbt build` failed at 09:40:48.729881 after 0.04 seconds
[0m09:40:48.730421 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104954920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104856b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104ba1a30>]}
[0m09:40:48.730632 [debug] [MainThread]: Flushing usage events
[0m09:40:48.834674 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
